### ISSUE TITLE
Members page

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/blog-next#16]
Fetch members (email and profpic) from PéK, and list em' on a page.
(Not that important)
Or it could be part of About us page see issue: #13

**Comment by OmTheTurtle** [comment]
I don't think we can fetch a group's member list from PéK automatically yet. And since a lot of people don't have a profile pic in PéK (and is often out-of-date), we should stick to git-managed content when implementing the members content.

**Comment by balintkiraly** [comment]
Would be great to implement endpoint for this, maybe it would be useful for other groups also. Perhaps it has a good impact too, it would force the members to keep their profile/groups up-to-date. However it's not that easy. We need to implement auth for the endpoints (API token or something similar) and add the opportunity for the users to hide their profile. So as @OmTheTurtle said the git-managed content would the best approach now. But I wouldn't reject the original suggestion either but I’d rather postpone it to later.
