### ISSUE TITLE
Animated logo

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/blog-next#33]
We could add a nice SVG animation for the large logo on the hero section like at https://konferencia.simonyi.bme.hu/

**Comment by triszt4n** [comment]
Simple explanation for how the simonyi animation works: https://youtu.be/9xrEZ6jqdik?t=2782

**Comment by triszt4n** [comment]
Some extra task: Make the frontpage hero fill the viewport (100vh or sth like that)
