### ISSUE TITLE
Favicon not loading everywhere

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/blog-next#55]
favicon is loaded with `../favicon.png` but when I navigate to a blog post `/post/asd`, then the favicon can't load from `/post/favicon.png`. Mend it.

**Comment by ahcodes** [comment]
I could try and see if I can fix this. Would you mind assigning me this issue? Thanks!

**Comment by triszt4n** [comment]
Yeah, sure, knock yourself out and thank you! Take a look at IndexLayout's Helmet component, you can find the favicon there

**Comment by triszt4n** [comment]
All right it seems, that in order to make a pull request to the repo, you would have to be a member of the organization or given special rights, but that's out of my authority. I'm gonna have to unassign you from this issue, but thanks for the enthusiasm!

**Comment by ahcodes** [comment]
Oh, no worries!
