### ISSUE TITLE
Background for non-main pages

### ISSUE THREAD

**Issue by OmTheTurtle** [kir-dev/blog-next#85]
For the pages like courses, about us and alike, we can add a nice background to make the site more interesting instead of just being plain white (something like at [cogito's landing page](https://cogito.study/))

**Comment by triszt4n** [comment]
# Everything's fine :fire: :dog: :+1:  :fire: 

![Screenshot from 2021-02-08 18-58-03](https://user-images.githubusercontent.com/60111772/123563304-495f4e80-d7b4-11eb-956b-c3a258ab97b5.png)
